defaults:
  - _self_
  - cluster: bcm
  - search_config: gpt3/5b
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null

run_training_hp_search: True
run_inference_hp_search: False

results:
    base: /lustre/fsw/joc/xren/results/nemo_megatron/nemo
    dir: gpt3_hp/5b
nemo_code: /home/xren/my_work/nemo_megatron/nemo/NeMo
nemo_launcher_code: /home/xren/my_work/nemo_megatron/nemo/NeMo-Megatron-Launcher

#preproc_data: /lustre/fsw/joc/big_nlp/t5/dataset/Pile # T5 dataset
preproc_data: /lustre/fsw/joc/big_nlp/gpt3/prepare_dataset/the_pile/train # GPT3 dataset

cluster_type: bcm  # bcm or bcp
auto_configurator_path: ${nemo_launcher_code}/auto_configurator  # Path to the location of auto_configurator codebase.
launcher_scripts_path: ${auto_configurator_path}/../launcher_scripts
base_results_dir: ${results.base}/${results.dir}
data_dir: ${preproc_data}

training_container: nvcr.io/nvidia/nemo:24.07
container_mounts:
    - ${nemo_code}:/opt/NeMo

wandb:  # Weights and Biases (W&B) logging.
  enable: False  # Whether to save logs to W&B.
  api_key_file: ${nemo_launcher_code}/wandb/wandb_api_key # Path to the file where the w&B api key is stored. Key must be on the first line.
  project: nemo-megatron-autoconfig # Name of the W&B project to store the logs in. The name of the run will be populated automatically.

# Do not modify the code below.
search_config_value: ${hydra:runtime.choices.search_config}
